### ISSUE TITLE
Empty notifications on post edits

### ISSUE THREAD

**Issue by yura04** [captainepoch/husky#111] opened 2024-11-05 17:51 UTC
## General description of the issue

In case of somebody editing their posts husky receives empty notifications with no content

## Husky information

- Husky version: 1.6.0
- Android version: 14

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Interact with others post
2. Ask them to edit it.
3. Receive empty notification with no information.

Notification of post edit shown in Tusky
![Notification of post edit shown in last Tusky](https://github.com/user-attachments/assets/6fb31974-34a3-491c-972a-1a7a1bef2c22)

Empty notification in Husky
![Empty notification in Husky](https://github.com/user-attachments/assets/34369c67-f4bb-45de-bf09-4336b7089f03)

## Where did you get Husky from:

- [x] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment] 2024-11-25 07:24
I didn't even noticed this, I'll try to fix it asap, thanks!

**Comment by captainepoch** [comment] 2024-11-25 15:03
I'm unable to reproduce this, could you share more context, please?

**Comment by yura04** [comment] 2024-11-25 15:57
It appeared to be more complicated. You need 2 accounts.
1. Account A: post message
2. Account B: boost the message
3. Account A: edit boosted message after boost have appeared in notifications
4. Account B: receive empty notification

Looks like it doesn't work with regular replies/favorites. Only with boosts.

**Comment by captainepoch** [comment] 2024-11-25 21:26
Ah, got it, thanks!

**Comment by captainepoch** [comment] 2024-11-26 17:20
This should be fixed in the PR #114 

![Screenshot_20241126_181731](https://github.com/user-attachments/assets/bd8ebd97-f6bb-4964-8437-ff8eb0bf42f8)

**Closed** 2024-11-27 05:37 UTC
Labels: bug
